name: Publish Python Package to PyPI

on:
  release:
    types: [published]  # Triggers when you publish a GitHub Release

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # Required for trusted publishing (if used)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # Use your desired Python version

    - name: Install build tool
      run: pip install build

    - name: Build the package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
